#pragma config(Motor,  port2,           armHeight,     tmotorNormal, openLoop)
#pragma config(Motor,  port3,           armLength,     tmotorNormal, openLoop)
#pragma config(Motor,  port4,           lazySuzan,     tmotorNormal, openLoop)
#pragma config(Motor,  port5,           gripper,       tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Function Prototypes
void setArmHeight();
void setArmLength();
void setLazySuzan();
void setGripper();

// Program entry point
task main()
{
	while (true)
	{
		setArmHeight();
		setArmLength();
		setLazySuzan();
		setGripper();
	}
}

void setGripper()
{
	if (vexRT[Btn5U] == 1)
	{
		motor[gripper] = 127;
	}
	else
	{
		motor[gripper] = 50;
	}
}

void setArmHeight()
{
	motor[armHeight] = vexRT[Ch3] / 2;
}

void setArmLength()
{
	if (vexRT[Btn6U] == 1)
		{
			motor[armLength] = 63;
		}
		else if (vexRT[Btn6D] == 1)
		{
			motor[armLength] = -63;
		}
		else
		{
			motor[armLength] = 0;
		}
}

void setLazySuzan()
{
	if (vexRT[Btn8L] == 1)
	{
		motor[lazySuzan] = -127;
	}
	else if (vexRT[Btn8R] == 1)
	{
		motor[lazySuzan] = 127;
	}
	else
	{
		motor[lazySuzan] = vexRT[Ch1] / 4;
	}
}
